INSERT INTO "USER"(username)
VALUES ('user');

INSERT INTO "USER"(username)
VALUES ('user1');

INSERT INTO "USER_WALLET"("USER_ID","SYMBOL","ACCOUNTBALANCE")
VALUES ((SELECT id FROM "USER" WHERE username = 'user'), 'USDT', '50000.00');